### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by igreulich** [pklingem/.janus#1]
@pklingem I was wondering if you might help me install this?

I created ~/.janus and git cloned this repo into it, but now what?

Help!

**Comment by pklingem** [comment]
Check out the Janus docs, specifically this portion:
https://github.com/carlhuda/janus#customization

**Comment by igreulich** [comment]
So initially I did that, and simply cloned your .janus modules, based on the `git clone` directions.

That did nothing for me, I got some submodule links, but no actual code. Basically I had to install each of the plugins manually with git submodule add. 

Basically you can't clone a repo with submodules, and expect to get the submodules to work (at least not readily).

Thanks!

**Comment by pklingem** [comment]
Oh yeah... forgot they were submodules, I'll update the readme, it should
be:

`git submodule init`
`git submodule update`

**Comment by igreulich** [comment]
Unfortunately, this was one of those time I didn't know enough to be able
to formulate a question to ask Google or StackOverflow.

Thanks!

---
- Ian

Sent from my iPad

On Aug 20, 2013, at 8:54 AM, Patrick Klingemann notifications@github.com
wrote:

Oh yeah... forgot they were submodules, I'll update the readme, it should
be:

`git submodule init`
`git submodule update`

On Tue, Aug 20, 2013 at 1:36 AM, Ian Greulich notifications@github.comwrote:

> So initially I did that, and simply cloned your .janus modules, based on
> the git clone directions.
> 
> That did nothing for me, I got some submodule links, but no actual code.
> Basically I had to install each of the plugins manually with git
> submodule
> add.
> 
> Basically you can't clone a repo with submodules, and expect to get the
> submodules to work (at least not readily).
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/pklingem/.janus/issues/1#issuecomment-22923645>
> .

—
Reply to this email directly or view it on
GitHubhttps://github.com/pklingem/.janus/issues/1#issuecomment-22942563
.

**Comment by pklingem** [comment]
@igreulich I should also mention: both of the plugins in this repo have better alternatives, namely:

http://vimcasts.org/episodes/aligning-text-with-tabular-vim/
https://github.com/godlygeek/tabular

https://powerline.readthedocs.org/en/latest/overview.html#installation
https://github.com/Lokaltog/powerline

I suppose I should update my repo :/

**Comment by igreulich** [comment]
I looked into the newer powerline, and for my wants, the version you have is just fine. Though strictly speaking, I might not actually have the same revision. I have the latest version before the newest version was ready.  

I didn't know about the better/newer align.

I might be on the verge of falling down the vim plugin rabbit hole...  

## 

Ian Greulich

Email: ian@greulich.me (mailto:ian@jackrussellsoftware.com)
Web: www.greulich.me (http://www.greulich.me)
